import type { CollectionTable } from '../schema.types';
import { parseJson } from '../schema.helpers';

export const EGGS_TABLE: CollectionTable = {
  namespace: 'eggs',
  table: 'eggs',
  keyColumn: 'egg_id',
  columns: [
    { name: 'nest_id', type: 'VARCHAR(160) NOT NULL' },
    { name: 'name', type: 'VARCHAR(255) NOT NULL' },
    { name: 'description', type: 'TEXT' },
    { name: 'images', type: 'TEXT NOT NULL' },
    { name: 'docker_images', type: 'TEXT NOT NULL' },
    { name: 'startup', type: 'TEXT NOT NULL' },
    { name: 'stop_command', type: "TEXT NOT NULL DEFAULT ''" },
    { name: 'startup_done', type: "TEXT NOT NULL DEFAULT ''" },
    { name: 'environment', type: 'TEXT NOT NULL' },
    { name: 'variables', type: 'TEXT NOT NULL' },
    { name: 'install', type: 'TEXT' },
    { name: 'config_files', type: 'TEXT' },
    { name: 'raw', type: 'TEXT' },
  ],
  toRow: (v: any) => [
    v.nestId, v.name, v.description || null,
    JSON.stringify(v.images || []),
    JSON.stringify(v.dockerImages || []),
    v.startup || '',
    v.stopCommand || '',
    v.startupDone || '',
    JSON.stringify(v.environment || {}),
    JSON.stringify(v.variables || []),
    v.install ? JSON.stringify(v.install) : null,
    v.configFiles ? JSON.stringify(v.configFiles) : null,
    v.raw ? JSON.stringify(v.raw) : null,
  ],
  fromRow: (r: any) => ({
    id: r.egg_id,
    nestId: r.nest_id,
    name: r.name,
    description: r.description || undefined,
    images: parseJson(r.images, []),
    dockerImages: parseJson(r.docker_images, []),
    startup: r.startup || '',
    stopCommand: r.stop_command || '',
    startupDone: r.startup_done || '',
    environment: parseJson(r.environment, {}),
    variables: parseJson(r.variables, []),
    install: r.install ? parseJson(r.install, undefined) : undefined,
    configFiles: r.config_files ? parseJson(r.config_files, {}) : undefined,
    raw: r.raw ? parseJson(r.raw, undefined) : undefined,
  }),
  indexes: [
    { name: 'idx_eggs_nest', columns: 'nest_id' },
  ],
};
