import type { CollectionTable } from '../schema.types';
import { parseJson, ts } from '../schema.helpers';

export const SERVER_PLANS_TABLE: CollectionTable = {
  namespace: 'server-plans',
  table: 'server_plans',
  keyColumn: 'plan_id',
  columns: [
    { name: 'name', type: 'VARCHAR(160) NOT NULL' },
    { name: 'enabled', type: 'BOOLEAN NOT NULL DEFAULT TRUE' },
    { name: 'external_ids', type: 'TEXT' },
    { name: 'egg_id', type: 'VARCHAR(160) NOT NULL' },
    { name: 'egg_change_allowed', type: 'BOOLEAN NOT NULL DEFAULT FALSE' },
    { name: 'allowed_egg_ids', type: 'TEXT' },
    { name: 'location', type: 'VARCHAR(160)' },
    { name: 'node_id', type: "VARCHAR(120) NOT NULL DEFAULT 'auto-least-memory'" },
    { name: 'memory_mb', type: 'INTEGER NOT NULL' },
    { name: 'disk_mb', type: 'INTEGER NOT NULL' },
    { name: 'cpu_limit_percentage', type: 'INTEGER NOT NULL DEFAULT 100' },
    { name: 'cpu_cores', type: '${real}' },
    { name: 'cpu_pinning', type: 'BOOLEAN NOT NULL DEFAULT FALSE' },
    { name: 'cpu_pinned_threads', type: "VARCHAR(255) NOT NULL DEFAULT ''" },
    { name: 'swap_memory_mb', type: 'INTEGER NOT NULL DEFAULT 0' },
    { name: 'swap_memory_storage', type: "VARCHAR(16) NOT NULL DEFAULT 'general'" },
    { name: 'databases_enabled', type: 'BOOLEAN NOT NULL DEFAULT FALSE' },
    { name: 'database_limit', type: 'INTEGER NOT NULL DEFAULT 0' },
    { name: 'database_memory_mb', type: 'INTEGER NOT NULL DEFAULT 512' },
    { name: 'database_disk_mb', type: 'INTEGER NOT NULL DEFAULT 1024' },
    { name: 'database_cpu_limit_percentage', type: 'INTEGER NOT NULL DEFAULT 50' },
    { name: 'database_cpu_cores', type: '${real}' },
    { name: 'database_docker_image', type: "VARCHAR(255) NOT NULL DEFAULT 'mariadb:latest'" },
    { name: 'allowed_database_types', type: 'TEXT' },
    { name: 'database_port_range_mode', type: "VARCHAR(16) NOT NULL DEFAULT 'game'" },
    { name: 'database_port_range_start', type: 'INTEGER NOT NULL DEFAULT 33060' },
    { name: 'database_port_range_end', type: 'INTEGER NOT NULL DEFAULT 33160' },
    { name: 'backup_limit', type: 'INTEGER NOT NULL DEFAULT 0' },
    { name: 'docker_image', type: 'VARCHAR(255)' },
    { name: 'variables', type: 'TEXT' },
    { name: 'created_at', type: '${date} NOT NULL' },
  ],
  toRow: (v: any) => [
    v.name, v.enabled, JSON.stringify(v.externalIds || []),
    v.eggId, v.eggChangeAllowed, JSON.stringify(v.allowedEggIds || []),
    v.location || null, v.nodeId,
    v.memoryMb, v.diskMb, v.cpuLimitPercentage, null,
    Boolean(v.cpuPinnedThreads), v.cpuPinnedThreads || '', Number(v.swapMemoryMb || 0), v.swapMemoryStorage || 'general',
    v.databasesEnabled, v.databaseLimit,
    v.databaseMemoryMb, v.databaseDiskMb,
    v.databaseCpuLimitPercentage, v.databaseCpuCores ?? null,
    v.databaseDockerImage,
    JSON.stringify(v.allowedDatabaseTypes || []),
    v.databasePortRangeMode,
    v.databasePortRangeStart, v.databasePortRangeEnd,
    v.backupLimit, v.dockerImage || null,
    JSON.stringify(v.variables || {}),
    v.createdAt,
  ],
  fromRow: (r: any) => ({
    id: r.plan_id,
    name: r.name,
    enabled: Boolean(r.enabled),
    externalIds: parseJson(r.external_ids, []),
    eggId: r.egg_id,
    eggChangeAllowed: Boolean(r.egg_change_allowed),
    allowedEggIds: parseJson(r.allowed_egg_ids, []),
    location: r.location || '',
    nodeId: r.node_id,
    memoryMb: Number(r.memory_mb),
    diskMb: Number(r.disk_mb),
    cpuLimitPercentage: Number(r.cpu_limit_percentage),
    cpuPinnedThreads: String(r.cpu_pinned_threads || ''),
    swapMemoryMb: Number(r.swap_memory_mb || 0),
    swapMemoryStorage: r.swap_memory_storage === 'server' ? 'server' : 'general',
    databasesEnabled: Boolean(r.databases_enabled),
    databaseLimit: Number(r.database_limit),
    databaseMemoryMb: Number(r.database_memory_mb),
    databaseDiskMb: Number(r.database_disk_mb),
    databaseCpuLimitPercentage: Number(r.database_cpu_limit_percentage),
    databaseCpuCores: r.database_cpu_cores != null ? Number(r.database_cpu_cores) : undefined,
    databaseDockerImage: r.database_docker_image,
    allowedDatabaseTypes: parseJson(r.allowed_database_types, []),
    databasePortRangeMode: r.database_port_range_mode,
    databasePortRangeStart: Number(r.database_port_range_start),
    databasePortRangeEnd: Number(r.database_port_range_end),
    backupLimit: Number(r.backup_limit),
    dockerImage: r.docker_image || undefined,
    variables: parseJson(r.variables, {}),
    createdAt: ts(r.created_at),
    updatedAt: ts(r.updated_at),
  }),
  indexes: [
    { name: 'idx_server_plans_enabled', columns: 'enabled' },
  ],
};
