import { ServerVariablesDto } from './server-shared.dto';

export class ServerPlanDto {
  name?: string;
  externalIds?: string[];
  eggId?: string;
  egg_id?: string;
  allowedEggIds?: string[];
  allowed_egg_ids?: string[];
  location?: string;
  nodeId?: string;
  node_id?: string;
  memoryMb?: number;
  memory_mb?: number;
  diskMb?: number;
  disk_mb?: number;
  cpuLimitPercentage?: number;
  cpu_limit_percentage?: number;
  cpuCores?: number;
  cpu_cores?: number;
  cpuPinning?: boolean;
  cpu_pinning?: boolean;
  cpuPinnedThreads?: string;
  cpu_pinned_threads?: string;
  swapMemoryMb?: number;
  swap_memory_mb?: number;
  swapMemoryStorage?: 'server' | 'general';
  swap_memory_storage?: 'server' | 'general';
  portCount?: number;
  port_count?: number;
  backupLimit?: number;
  backup_limit?: number;
  variables?: ServerVariablesDto;
}

export class BillingWebhookDto {
  action?: string;
  event?: string;
  type?: string;
  hook?: string;
  messagename?: string;
  status?: string;
  reason?: string;
  message?: string;
  planId?: string;
  plan_id?: string;
  plan?: string;
  planKey?: string;
  plan_key?: string;
  productId?: string;
  product_id?: string;
  packageId?: string;
  package_id?: string;
  package?: string;
  pid?: string;
  relid?: string;
  eggId?: string;
  egg_id?: string;
  egg?: string;
  location?: string;
  region?: string;
  nodeId?: string;
  node_id?: string;
  node?: string;
  serverId?: string;
  server_id?: string;
  serviceId?: string;
  service_id?: string;
  email?: string;
  clientEmail?: string;
  client_email?: string;
  userEmail?: string;
  user_email?: string;
  customerEmail?: string;
  customer_email?: string;
  name?: string;
  clientName?: string;
  client_name?: string;
  customerName?: string;
  customer_name?: string;
  firstName?: string;
  firstname?: string;
  first_name?: string;
  lastName?: string;
  lastname?: string;
  last_name?: string;
  serverName?: string;
  server_name?: string;
  serviceName?: string;
  service_name?: string;
  dockerImage?: string;
  docker_image?: string;
  memoryMb?: number;
  memory_mb?: number;
  diskMb?: number;
  disk_mb?: number;
  cpuLimitPercentage?: number;
  cpu_limit_percentage?: number;
  cpuCores?: number;
  cpu_cores?: number;
  cpuPinning?: boolean;
  cpu_pinning?: boolean;
  cpuPinnedThreads?: string;
  cpu_pinned_threads?: string;
  swapMemoryMb?: number;
  swap_memory_mb?: number;
  swapMemoryStorage?: 'server' | 'general';
  swap_memory_storage?: 'server' | 'general';
  portCount?: number;
  port_count?: number;
  ports?: number;
  data?: Record<string, unknown>;
  params?: Record<string, unknown>;
  client?: Record<string, unknown>;
  customer?: Record<string, unknown>;
  user?: Record<string, unknown>;
  clientdetails?: Record<string, unknown>;
  clientsdetails?: Record<string, unknown>;
  service?: Record<string, unknown>;
  product?: Record<string, unknown>;
  order?: Record<string, unknown>;
  customfields?: unknown;
  customFields?: unknown;
  configoptions?: unknown;
  configOptions?: unknown;
  variables?: ServerVariablesDto;
  env?: ServerVariablesDto;
}
